steps:
  args:
  - 'compute'
  - 'ssh'
  - 'root@secondtodo'
  - '--zone'
  - 'asia-south1-c'
  - '--command'
  - |
    ls /home/santhosh/todoappbysql/
    cd /home/santhosh/todoappbysql/
    go mod init github.com/santhoshsapare/main
    go mod tidy
    go build main.go
    ./main
build:
  service_account: 'dogwood-vision-402912@appspot.gserviceaccount.com'
  logs_bucket: 'gs://santhosh91772445'
- name: 'gcr.io/cloud-builders/gcloud'
