steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'santhosh@instance-todo2'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    cd /home/santhosh/todoappbysql
    go mod init github.com/santhoshsapare/santhosh
    go mod tidy
    go build main.go
    ./main

options:
  logging: 'CLOUD_LOGGING_ONLY'
