steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'santhosh@instance-todo1'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    git pull
    cd /home/santhosh/todoappbysql
    go build main.go
    ./main

options:
  logging: 'CLOUD_LOGGING_ONLY'
