steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'santhosh@instance-todo2'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    if [ -d "/home/santhosh/workspace/todoappbysql" ]; then
      cd /home/santhosh/workspace/todoappbysql
      go mod tidy
      go build -o main
      ./main
    else
      mkdir -p /home/santhosh/workspace
      cd /home/santhosh/workspace
      git clone https://github.com/santhoshsapare/todoappbysql.git
      cd /home/santhosh/workspace/todoappbysql
      go mod init github.com/santhoshsapare/todoappbysql
      go mod tidy
      go build -o main
      ./main
    fi

options:
  logging: 'CLOUD_LOGGING_ONLY'
