steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'root@instance-1'
  - '--zone'
  - 'us-west4-b'
  - '--command'
  - |
    cd /home/santhosh/todoappbysql
    go build main.go
    ./main

options:
  logging: 'CLOUD_LOGGING_ONLY'
