steps:
- name: 'gcr.io/cloud-builders/go'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "export GOPATH=/home/santhosh/gopath/go" >> ~/.bashrc
      echo "export PATH=/home/santhosh/go/bin:/home/santhosh/go/bin" >> ~/.bashrc
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'santhosh@instance-1'
  - '--zone'
  - 'us-west4-b'
  - '--command'
  - |
    cd /home/santhosh/todoappbysql
    go build main.go
    ./main

options:
  logging: 'CLOUD_LOGGING_ONLY'
